language: python
cache: pip
dist: xenial
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- nightly
install: pip install -r requirements.txt
script: nosetests --nocapture --verbose
deploy:
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  on:
    branch: master
  user: __token__
  password:
    secure: WhlnhfXVscO22QE4HfZxWOEUMhOa0LEWu5ROgh473T3xm15EEum2We/8jJikXrv9w+xkW9rDvQzTBfST3Y5aACvgQA58eS24Q3ziV5DXb+MwkH+7JaF8ItofusWiKXE+RDhhYY0KKvyvRMier+BYugkzfKvXwBfGnWmtHGSBG/gk/NSRXO2SC8JThn4mLQMUfgpny50CcVIOsvGuBWiMjGrYgUO1HVZIPq4C2n/vZeo9g+NwzUMcWOYxxyQ8oaFqeldp1Wcnqg+eiNP0ajkxheUcwnUoE9kiZxb2qQvEzwlvcjasQMdmNqBz4LP6asfWMGOBii/qYzVTTfuMO9rlJ6zGVJHy0x/QMpNXxwtoA/V8uuj0ru5fSWQ3w7BJvRhF71A9uAFPmPQEeuu7hMY0GbKIm8AjmCvW330Fdixd3Z/0SDH74LYyp4dEo+eyuLj3V3GFYkin7HP1yPOiBe21MIGY4iwg+1ERzsLX6EjVOYmu4C6kpX/K4fZV93LpMzXuNqsK1kdfcmiVkPvCAeVYMACFHZzEXWVZTBK4klxUaIQol33gQOKeLvvCIGFFXah71Yraeweiy4TIc42z/2X9UJcmHJ09J2M6gIh7GZS3NwSJt5tWRu1ZmymCGj+LYs+Y+kO//B9Oo1jvcDindRdZGztf3Yop1qGKNekw2S+ShwQ=
